#!/usr/bin/env bash

# -d 判断文件夹
# -f 判断文件
# -x 判断是否有可执行权限

# 安装 ZI
if [ ! -d "${HOME}/.zi" ]; then
    echo "正在安装 ZI 插件" 1>&2
    git clone https://github.com/z-shell/zi.git ~/.zi/bin
fi

# 安装 NvChad
if [ ! -d "${HOME}/.config/nvim" ]; then
    echo "正在安装 NvChad" 1>&2
    git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
fi

# 安装 TMUX 插件
if [ ! -d "${HOME}/.config/tmux" ]; then
    echo "正在安装 TMUX 插件" 1>&2
    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
fi

# tig 历史记录文件位置
if [ ! -d "${HOME}/.local/share/tig" ]; then
    mkdir -p ${HOME}/.local/share/tig
fi

# less 历史记录文件位置
if [ ! -d "${HOME}/.local/share/less" ]; then
    mkdir -p ${HOME}/.local/share/less
fi

# mycli 历史文件记录位置
if [ ! -d "${HOME}/.local/share/mycli" ]; then
    mkdir -p ${HOME}/.local/share/mycli
fi

# histdb 命令历史记录位置
if [ ! -d "${HOME}/.local/share/histdb/.git" ]; then
    echo "正在安装 histdb"
    git clone https://github.com/hubogle/histdb.git ~/.local/share/histdbNew
    rm -rf ~/.local/share/histdb && mv ~/.local/share/histdbNew ~/.local/share/histdb
fi

# im-select 脚本安装
if [ ! -f "${BREW_PATH}/im-select" ]; then
    echo "安装 im-select"
    cp $DOTFILES_DIRS/config/im-select/im-select $BREW_PATH/im-select
    chmod +x $BREW_PATH/im-select
fi
