#!/usr/bin/env bash

# -d 判断文件夹
# -f 判断文件
# -x 判断是否有可执行权限

# 安装 NvChad
if [ ! -d "${HOME}/.config/nvim" ]; then
    echo "正在安装 NvChad" 1>&2
    git clone https://github.com/NvChad/starter ~/.config/nvim
fi

# ipython 文件位置
if [ ! -d "${HOME}/.local/state/ipython" ]; then
	mkdir -p ${HOME}/.local/state/ipython
fi

# zsh_history 文件位置
if [ ! -d "${HOME}/.local/state/zsh" ]; then
	mkdir -p ${HOME}/.local/state/zsh
fi

# less 历史记录文件位置
if [ ! -d "${HOME}/.local/state/less" ]; then
    mkdir -p ${HOME}/.local/state/less
fi

# mycli 历史文件记录位置
if [ ! -d "${HOME}/.local/state/mycli" ]; then
    mkdir -p ${HOME}/.local/state/mycli
fi

# im-select 脚本安装
if [ ! -f "${BREW_PATH}/im-select" ]; then
    echo "安装 im-select"
    cp $DOTFILES_DIRS/config/im-select/im-select $BREW_PATH/im-select
    chmod +x $BREW_PATH/im-select
fi

# alacritty themes
if [ ! -d "${HOME}/.config/alacritty/themes" ]; then
    echo "安装 alacritty theme"
    git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
fi
