#!/usr/bin/env bash

# -d 判断文件夹
# -f 判断文件
# -x 判断是否有可执行权限

# 安装 NvChad
if [ ! -d "${HOME}/.config/nvim" ]; then
    echo "正在安装 NvChad" 1>&2
    git clone https://github.com/NvChad/starter ~/.config/nvim
fi

# 安装 TMUX 插件
# if [ ! -d "${HOME}/.config/tmux" ]; then
#     echo "正在安装 TMUX 插件" 1>&2
#     git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
# fi

# ipython 文件位置
if [ ! -d "${HOME}/.local/state/ipython" ]; then
	mkdir -p ${HOME}/.local/state/ipython
fi

# zsh_history 文件位置
if [ ! -d "${HOME}/.local/state/zsh" ]; then
	mkdir -p ${HOME}/.local/state/zsh
fi

# tig 历史记录文件位置
if [ ! -d "${HOME}/.local/state/tig" ]; then
    mkdir -p ${HOME}/.local/state/tig
fi

# less 历史记录文件位置
if [ ! -d "${HOME}/.local/state/less" ]; then
    mkdir -p ${HOME}/.local/state/less
fi

# mycli 历史文件记录位置
if [ ! -d "${HOME}/.local/state/mycli" ]; then
    mkdir -p ${HOME}/.local/state/mycli
fi

# alacritty themes
if [ ! -d "${HOME}/.config/alacritty/themes" ]; then
    echo "安装 alacritty theme"
    git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
fi
