patch:
  schema_list:
    - schema: rime_mint

  # ascii_mode、inline、no_inline、vim_mode 等等设定，可参考 /Library/Input Methods/Squirrel.app/Contents/SharedSupport/squirrel.yaml
  # 中西文切换
  #
  # 【good_old_caps_lock】 CapsLock 切换到大写或切换中英。
  # （macOS 偏好设置的优先级更高，如果勾选【使用大写锁定键切换“ABC”输入法】则始终会切换输入法）
  #
  # 切换中英：
  # 不同的选项表示：打字打到一半时按下了 CapsLock、Shift、Control 后：
  # commit_code  上屏原始的编码，然后切换到英文
  # commit_text  上屏拼出的词句，然后切换到英文
  # clear        清除未上屏内容，然后切换到英文
  # inline_ascii 无输入时，切换中英；有输入时，切换到临时英文模式，按回车上屏后回到中文状态
  # noop         屏蔽快捷键，不切换中英，但不要屏蔽 CapsLock
  ascii_composer:
    # 定义切换到西文模式的快捷键
    switch_key:
      Caps_Lock: commit_code  # 按下 Caps Lock 会直接上屏
      Control_L: noop  # 按下左 Control 键不做任何操作
      Control_R: noop  # 按下右 Control 键不做任何操作
      Shift_L: noop  # 按下左 Shift 键会直接上屏
      Shift_R: inline_ascii  # 按下右 Shift 键会临时切换到西文模式
    good_old_caps_lock: true  # 启用经典的 Caps Lock 开启西文模式的方式
