# Rime dictionary
# mim: set ts=8 sw=8 noet:
# encoding: utf-8
# easy_en - Easy English

---
name: easy_en
version: "0.2"
sort: by_weight
use_preset_vocabulary: false
import_tables:
  - en_dicts/en     # 原装词库
  - en_dicts/en_ext # 自己补充的词库
  - en_dicts/cn_en  # 中英混输词库
