distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.18
install_time: "Wed Jun  1 16:20:08 2022"
installation_id: Rime
rime_version: 1.11.2
sync_dir: "~/Documents/File"
update_time: "Tue May  7 19:57:34 2024"
