distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.15.2
install_time: "Wed Jun  1 16:20:08 2022"
installation_id: "Rime"
sync_dir: "/Users/hubo/Documents/File"
rime_version: 1.7.3
