distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.16.1
install_time: "Wed Jun  1 16:20:08 2022"
installation_id: Rime
rime_version: 1.8.4
sync_dir: "/Users/hubo/Documents/File"
update_time: "Wed Feb  1 21:19:44 2023"