# Rime dictionary
# encoding: utf-8
# Luna Pinyin Extended Dictionary(Basic)  - 明月拼音扩充词库（基本）

---
name: luna_pinyin.extended      # 词库名
version: "2021.02.07"
sort: by_weight                 # by_weight（按词频高低排序）或 original（保持原码表中的顺序）
vocabulary: essay-zh-hans

# 词库地址: https://github.com/iDvel/rime-settings/tree/master/cn_dicts
import_tables:
  - cn_dicts/8105   # 《通用汉字规范表》8105 字字表
  - cn_dicts/main    # 系统词库
  - cn_dicts/ext     # 扩展词库
  - cn_dicts/others  # 一些杂项
  - cn_dicts/zhwiki  # 百万维基词库
