# Rime schema
# vim: set sw=2 sts=2 et:
# encoding: utf-8

schema:
  schema_id: melt_eng
  name: Easy English Nano
  version: "0.2.2"
  author:
    - Patrick <ipatrickmac@gmail.com>
    - tumuyan <tumuyan@21cn.com>
  description:
    Easy English Nano，只包含少量常用词汇，方便中英文混合输入度方案调用。

switches:
  - name: ascii_mode
    reset: 0
    states: [ ASCII-OFF, ASCII-ON ]

engine:
  processors:
    - ascii_composer
    - key_binder
    - speller
    - recognizer
    #關閉標點符號轉換（對應symbols.yaml）    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - matcher
    - ascii_segmentor
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - table_translator
    - punct_translator
  filters:
    - uniquifier

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"
  algebra:
    __include: algebra_rime_ice         # 全拼
    
translator:
  dictionary: melt_eng
  spelling_hints: 9
  
# 通用的派生规则
algebra_common:
  # 数字派生
  - derive/1([4-7|9])/$1teen/
  - derive/11/eleven/
  - derive/12/twelve/
  - derive/13/thirteen/
  - derive/15/fifteen/
  - derive/18/eighteen/
  - derive/0/o/ # 如 1000 -> oneOOO
  - derive/0/O/
  - derive/0/zero/
  - derive/1/one/
  - derive/10/ten/
  - derive/2/to/
  - derive/2/two/
  - derive/3/three/
  - derive/4/for/
  - derive/4/four/
  - derive/5/five/
  - derive/6/six/
  - derive/7/seven/
  - derive/8/eight/
  - derive/9/nine/
  # 符号派生
  - derive/\+/plus/
  - derive/\./dot/
  - derive/@/at/
  - derive/-/hyphen/
  - derive/#/hash/
  - derive/#/number/
  - derive/#/sharp/
  - derive/♯/sharp/
  - derive / slash
  - derive/&/and/
  - derive/%/percent/
  # 派生无单个特殊字符的拼写
  - derive/[.]//
  - derive/[+]//
  - derive/[@]//
  - derive/[-]//
  - derive/[_]//
  # 派生无任何非字母数字字符的拼写
  - derive/[^a-zA-Z0-9]//
  # 禁用非英文、数字开头的编码
  - erase/^[^a-zA-Z0-9].+$/
  # 全小写
  - derive/^.+$/\L$0/
  # 全大写
  - derive/^.+$/\U$0/
  # 首字母大写
  - derive/^./\U$0/
  # 前 2~10 个字母大写
  - derive/^([a-z]{2})/\U$1/
  - derive/^([a-z]{3})/\U$1/
  - derive/^([a-z]{4})/\U$1/
  - derive/^([a-z]{5})/\U$1/
  - derive/^([a-z]{6})/\U$1/
  - derive/^([a-z]{7})/\U$1/
  - derive/^([a-z]{8})/\U$1/
  - derive/^([a-z]{9})/\U$1/
  - derive/^([a-z]{10})/\U$1/

# 全拼
algebra_rime_ice:
  __include: algebra_common
  __append:
    - derive/(?<!\d)1([1-9])(?!\d)/shi$1/
    - derive/([1-9])0000(?!0)/$1wan/
    - derive/([1-9])000(?!0)/$1qian/
    - derive/([1-9])00(?!0)/$1bai/
    - derive/([2-9])0(?!0)/$1shi/
    - derive/(?<!\d)([2-9])([1-9])(?!\d)/$1shi$2/
    - derive/\./dian/
    - derive/10/shi/
    - derive/0/ling/
    - derive/1/yi/
    - derive/2/er/
    - derive/2/liang/
    - derive/3/san/
    - derive/4/si/
    - derive/5/wu/
    - derive/6/liu/
    - derive/7/qi/
    - derive/8/ba/
    - derive/9/jiu/
    - derive/\+/jia/
    - derive/#/jing/

key_binder:
  import_preset: default

punctuator:
  import_preset: default

recognizer:
  import_preset: default
