patch:
  menu:
    page_size: 9
  punctuator:
    import_preset: symbols
    # 定义部分半角字符
    half_shape:
        "#": "#"
        "*": "*"
        '.' : { commit: 。 }
        "`": "`"
        "~": "~"
        "@": "@"
        "=": "="
        "/": "/"
        '\': "、"
        "_" : "──"
        "'": "'"
        '"': '"'
        ';': ';'
        "[": ["【", "["]
        "]": ["】", "]"]
        "$": ["¥", "$", "€", "£", "¢", "¤"]
        "<": ["《", "〈", "«", "<"]
        ">": ["》", "〉", "»", ">"]
  key_binder:
    import_preset: default
    # Lua 配置: shijian.lua 的引导符，涉及：日期、时间、节日、节气、生日、问候模板等功能
    # accept，实际接受的按键
    # send，输出效果
    # toggle，切换开关
    # when，作用范围
    # 按住 control + 符号就是小写
    shijian_keys: ["o"]
    bindings:
      - {accept: "Control+Shift+E", toggle: emoji_suggestion, when: always}   # Emoji 快捷键
      - {accept: minus, send: Page_Up, when: paging}     # 使用`-`进行向上翻页（第一页时候无效）
      - {accept: equal, send: Page_Down, when: has_menu} # 使用`=`进行向下翻页
      # 选词
      - { when: composing, accept: Shift+Tab, send: Left }
      - { when: composing, accept: Tab, send: Right }              # tab 选择下一个
      # Emacs 风格的快捷键
      - { when: composing, accept: Control+p, send: Up }
      - { when: composing, accept: Control+n, send: Down }
      - { when: composing, accept: Control+b, send: Left }
      - { when: composing, accept: Control+f, send: Right }

      # 翻页
      - { when: paging, accept: minus, send: Page_Up }             # 编码窗口翻页
      - { when: has_menu, accept: equal, send: Page_Down }
      - { when: paging, accept: comma, send: Page_Up }             # 候选窗口翻页
      - { when: has_menu, accept: period, send: Page_Down }