# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 18 # column width relative to the terminal window
    min_width: 15 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 65
    min_width: 45
  snippet:
    color: red

finder:
  command: fzf # equivalent to the --finder option
  overrides: '--with-nth 1,2 --height 20 --reverse --ansi' # equivalent to the --fzf-overrides option
  overrides_var: '--height 20' # equivalent to the --fzf-overrides-var option

cheats:
  paths:
    # - ~/Documents/File/cheats
    - ~/Library/Application Support/navi

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

# shell:
  # command: /usr/local/bin/zsh # shell used for shell out. possible values: bash, zsh, dash, ...
  # finder_command: bash # similar, but for fzf's internals
