#!/usr/bin/env bash

RIME_DIR=~/Library/Rime
# 同步 rime 自定义词库
if [ -d "$RIME_DIR" ]; then
  ln -sfn $DOTFILES_DIRS/config/rime/default.custom.yaml $RIME_DIR/default.custom.yaml
  ln -sfn $DOTFILES_DIRS/config/rime/rime_mint.custom.yaml $RIME_DIR/rime_mint.custom.yaml
  ln -sfn $DOTFILES_DIRS/config/rime/squirrel.custom.yaml $RIME_DIR/squirrel.custom.yaml
fi