[tools]
# global tool versions go here
# you can set these with `mise use -g`

lua = '5.1'


[settings]
# configure `mise install` to always keep the downloaded archive
always_keep_download = true # deleted after install by default
always_keep_install = true  # deleted on failure by default

# configure messages displayed when entering directories with config files
# status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
